## unos jóvenes de un club de tecnología les pidió ayuda para analizar datos de su venta de pasteles.  Esperan reunir $200



El precio de venta de 3 artículos en la venta de pasteles es: $ 2 por un brownie, $ 1 por una galleta y $ 10 por un pastel. 

In [2]:
price = [2,1,10]
type(price)

list

El club vende 17 brownies, 40 galletas y un pastel. 

In [3]:
quantity_sold = [17,40,1]
type(quantity_sold)


list

In [4]:
import numpy as np


In [5]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)


numpy.ndarray

encontrar el dinero recaudado para cada tipo de elemento.  Queremos el precio * cantidad para cada elemento. Tratemos de multiplicar nuestros arrays.

In [6]:
price_array * quantity_sold_array

array([34, 40, 10])

costo de fabricación de cada uno de los artículos vendidos en la venta de pasteles.  Digamos que cuesta $0,25 para hacer un brownie, $0,50 una galleta y $5,00 un pastel.

In [7]:
cost_array = np.array ([0.25,0.50,5])

In [8]:
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


qué elementos obtuvieron un beneficio superior a $2 por elemento. 

In [9]:
profit_array > 2

array([False, False,  True])

El club también vende tartas por $7

In [10]:
price_array = np.append(price_array,7)
print(price_array)

[ 2  1 10  7]


el club quiere agregar los siguientes precios: $4,50 por dulces, $3 por una magdalena, $4 por una barra de pan de plátano y $9 por una torta.

In [11]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)



[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


comprobar el tipo de datos de los elementos del array

In [12]:
print(price_array.dtype)


float64


Resulta que nadie planea hacer una torta, así que quieren eliminar el precio de ese elemento del array.

In [13]:
price_array= np.delete(price_array, 7)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


Después el club decide subir el precio de los pasteles de $ 10 a $12.  Nuevamente, tendremos que identificar el elemento usando el índice.  Los pasteles están en el índice 2

In [14]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


 Actualicen el quantity_sold_array para incluir la venta de 2 tartas, 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano.  También se darán cuenta que una de las galletas que pensaron que se había vendido en realidad se cayó al suelo, así que editen quantity_sold_array de 40 a 39.  

Brownie, galleta, pastel,  tartas, dulces,magdalenas, pan de platano.

In [15]:
quantity_sold_array = np.append(quantity_sold_array, [3,2,16,5])
print(quantity_sold_array)

[17 40  1  3  2 16  5]


In [16]:
quantity_sold_array [1] = 39
print(quantity_sold_array)

[17 39  1  3  2 16  5]


correcion de orden.

In [17]:
quantity_sold_array [3] = 2
print(quantity_sold_array)

[17 39  1  2  2 16  5]


In [18]:
quantity_sold_array [4] = 3
print(quantity_sold_array)

[17 39  1  2  3 16  5]


Determinen la cantidad de dinero recaudado de la venta de cada elemento en la venta de la panadería. 

In [19]:
normal_sales_income_array = price_array * quantity_sold_array
print(normal_sales_income_array)

[34.  39.  12.  14.  13.5 48.  20. ]


Creen un array de NumPy "quantity_leftover" que incluya la cantidad de cada elemento restante al final de la venta: 2 pasteles, 1 tarta, 6 bandejas de dulces, 2 panes de plátano.  Pista: Asegúrense de incluir “0” de cada elemento que se haya vendido. ¿Por qué esto es importante cuando se crea un array?

por que cada elemento esta anexado a un indice. 

In [20]:
quantity_leftover_array = np.array ([0,0,2,1,6,0,2])

El club decide vender los elementos restantes a mitad de precio, y todo se venda rápidamente.  Determinen cuanto dinero se recaudó de la venta de liquidación.  

In [21]:
print(price_array)
discount_price=np.array(price_array)/2
print((discount_price))

[ 2.   1.  12.   7.   4.5  3.   4. ]
[1.   0.5  6.   3.5  2.25 1.5  2.  ]


In [22]:
leftover_income = discount_price * quantity_leftover_array
print(leftover_income)

[ 0.   0.  12.   3.5 13.5  0.   4. ]


¿Cuánto dinero total se recaudó de la venta de panadería (incluido la venta del precio total y los elementos liquidados)?



In [23]:
Total = leftover_income + normal_sales_income_array
print(Total)

[34.  39.  24.  17.5 27.  48.  24. ]


In [24]:
sum(Total)

213.5